Darazrt.Web/Models/Persons.cs
// <copyright file="Persons.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Darazrt.Web.Models
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Persons Model.
    /// </summary>
    public class Persons
    {
        /// <summary>
        /// Gets or sets person Id.
        /// </summary>
        [Display(Name = "Person Id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets keresztnev.
        /// </summary>
        [Display(Name = "Persons first name")]
        [Required]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets vezeteknev.
        /// </summary>
        [Display(Name = "Persons Last name")]
        [Required]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets lakcim.
        /// </summary>
        [Display(Name = "Persons Address")]
        public string Adress { get; set; }

        /// <summary>
        /// Gets or sets telefon.
        /// </summary>
        [Display(Name = "Person Phone Number")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or sets email.
        /// </summary>
        [Display(Name = "Person Email")]
        public string Email { get; set; }
    }
}

Darazrt.Web/Controllers/PersonsController.cs
// <copyright file="PersonsController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Darazrt.Web.Controllers
{
    using System.Collections.Generic;
    using AutoMapper;
    using DaraZrt.Logic;
    using Darazrt.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// The controller.
    /// </summary>
    public class PersonsController : Controller
    {
        private IDaraOffice logic;
        private IMapper mapper;
        private PersonListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonsController"/> class.
        /// </summary>
        /// <param name="logic">DaraOffice logic.</param>
        /// <param name="mapper">Mapper.</param>
        public PersonsController(IDaraOffice logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            vm = new PersonListViewModel();
            vm.EditedPerson = new Models.Persons();

            var persons = logic.GetAllPerson();
            vm.ListOfPersons = mapper.Map<ICollection<DaraZrt.Data.Models.Persons>, List<Models.Persons>>(persons);
        }

        /// <summary>
        /// GET index page.
        /// </summary>
        /// <returns>View page.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("PersonIndex", this.vm);
        }

        /// <summary>
        /// Details.
        /// </summary>
        /// <param name="id"> Persons Id. </param>
        /// <returns>View Page with Deatils.</returns>
        public IActionResult Details(int id)
        {
            return View("PersonDetails", GetPersonModel(id));
        }

        /// <summary>
        /// Remove Persons.
        /// </summary>
        /// <param name="id"> Person id.</param>
        /// <returns>Action. </returns>
        public IActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            logic.DeletePersons(logic.GetPerson(id));
            TempData["editResult"] = "Delet OK";
            return RedirectToAction(nameof(Index)); // View("PersonRemove", GetPersonModel(id));
        }

        /// <summary>
        /// Get EDIT.
        /// </summary>
        /// <param name="id">Persons Id.</param>
        /// <returns>View.</returns>
        public IActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedPerson = GetPersonModel(id);
            return View("PersonIndex", vm);
        }

        /// <summary>
        /// Posting the editing.
        /// </summary>
        /// <param name="person">Person.</param>
        /// <param name="editAction">EditAction.</param>
        /// <returns>PersonIndex.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Persons person, string editAction)
        {
            if (ModelState.IsValid && person != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.UpdatePersons(new DaraZrt.Data.Models.Persons() { LastName = person.LastName, FirstName = person.FirstName, Adress = person.Adress, Email = person.Email, PhoneNumber = person.PhoneNumber });
                }
                else
                {
                    logic.UpdatePersons(new DaraZrt.Data.Models.Persons() { Id = person.Id, LastName = person.LastName, FirstName = person.FirstName, Adress = person.Adress, Email = person.Email, PhoneNumber = person.PhoneNumber });
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedPerson = person;
                return View("PersonIndex", vm);
            }
        }

        private Models.Persons GetPersonModel(int id)
        {
            DaraZrt.Data.Models.Persons onePerson = this.logic.GetPerson(id);
            return this.mapper.Map<DaraZrt.Data.Models.Persons, Models.Persons>(onePerson);
        }
    }
}

Darazrt.Web/Views/Persons/PersonDetails.cshtml
@model Darazrt.Web.Models.Persons

@{
    @ViewData["Title"];

}

<h2>Datasheet of one car</h2>

@Html.ActionLink("Back To the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FirstName)</td>
        <td>@Html.DisplayFor(m => m.FirstName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LastName)</td>
        <td>@Html.DisplayFor(m => m.LastName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PhoneNumber)</td>
        <td>@Html.DisplayFor(m => m.PhoneNumber)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Adress)</td>
        <td>@Html.DisplayFor(m => m.Adress)</td>
    </tr>

</table>

Darazrt.Web/Views/Persons/PersonEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Darazrt.Web.Models.Persons

<h2>Person Edit</h2>

@using (Html.BeginForm("Edit", "Persons"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())
    <div class="editor-label">
        @Html.LabelFor(m => m.FirstName)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.FirstName)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.LastName)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.LastName)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Adress)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Adress)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Email)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Email)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.PhoneNumber)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.PhoneNumber)
    </div>
    <input type="submit" value="Send">

}

Darazrt.Web/Views/Persons/PersonIndex.cshtml
@model  Darazrt.Web.Models.PersonListViewModel
@{ 
    ViewData["Title"] = "Person Index";
}
<h2>
    Person Index
</h2>
<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("PersonEdit", Model.EditedPerson)
@await Html.PartialAsync("PersonsList", Model.ListOfPersons)

Darazrt.Web/Views/Persons/PersonsList.cshtml
@model IEnumerable<Darazrt.Web.Models.Persons>
<h2> Person List</h2>
@if (Model.Count()==0)
            {
                <p> No data in the database!</p>
            }
else
            {
                <table border="1">
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.First().FirstName)</th>
                        <th>@Html.DisplayNameFor(m => m.First().LastName)</th>
                        <th>@Html.DisplayNameFor(m => m.First().Adress)</th>
                        <th>@Html.DisplayNameFor(m => m.First().Email)</th>
                        <th>@Html.DisplayNameFor(m => m.First().PhoneNumber)</th>
                        <th>Datasheet</th>
                        <th>Delete</th>
                        <th>Modify</th>
                    </tr>
                    @foreach (var person in Model)
                {
                <tr>
                    <td>@Html.DisplayFor(m => person.FirstName)</td>
                    <td>@Html.DisplayFor(m => person.LastName)</td>
                    <td>@Html.DisplayFor(m => person.Adress)</td>
                    <td>@Html.DisplayFor(m => person.Email)</td>
                    <td>@Html.DisplayFor(m => person.PhoneNumber)</td>
                    <td>@Html.ActionLink("[SHOW]", "Details", new { id = person.Id })</td>
                    <td>@Html.ActionLink("[DEL]", "Remove", new { id = person.Id })</td>
                    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = person.Id })</td>
                </tr>
                }
                </table>
            }